# Generated by Django 3.2.4 on 2021-08-12 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bourse_refs_api', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('pattern_key', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PatternReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pattern_referee', to='quiz.pattern')),
                ('pattern_referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pattern_referrer', to='quiz.pattern')),
            ],
        ),
        migrations.CreateModel(
            name='PatternArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.pattern')),
            ],
            options={
                'unique_together': {('pattern', 'href')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalPatternActionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.pattern')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bourse_refs_api.stock')),
            ],
            options={
                'unique_together': {('stock', 'pattern', 'date')},
            },
        ),
    ]
