# Generated by Django 3.2.4 on 2021-08-14 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('pattern_key', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PatternReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pattern_referee', to='quiz.pattern')),
                ('pattern_referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pattern_referrer', to='quiz.pattern')),
            ],
        ),
        migrations.CreateModel(
            name='PatternArticle',
            fields=[
                ('href', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.pattern')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalPatternActionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.BigIntegerField(default=0)),
                ('date', models.DateField()),
                ('value', models.IntegerField(default=0)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.pattern')),
            ],
            options={
                'unique_together': {('pattern', 'stock_id', 'date')},
            },
        ),
    ]
