# Generated by Django 3.2.4 on 2021-08-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patternarticle',
            name='href',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='patternarticle',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='patternarticle',
            name='id',
        ),
    ]
