# Generated by Django 3.2.4 on 2021-08-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210812_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='historicalpatternactionpoint',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
