# Generated by Django 3.2.4 on 2021-08-17 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_leitnerbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatternStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('count', models.IntegerField()),
                ('change_mean', models.FloatField()),
                ('change_std', models.FloatField()),
                ('change_min', models.FloatField()),
                ('change_25', models.FloatField()),
                ('change_50', models.FloatField()),
                ('change_75', models.FloatField()),
                ('change_max', models.FloatField()),
                ('time_mean', models.IntegerField()),
                ('time_std', models.IntegerField()),
                ('time_min', models.IntegerField()),
                ('time_25', models.IntegerField()),
                ('time_50', models.IntegerField()),
                ('time_75', models.IntegerField()),
                ('time_max', models.IntegerField()),
                ('positive_rate', models.FloatField()),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.pattern')),
            ],
            options={
                'unique_together': {('pattern', 'value')},
            },
        ),
    ]
